### PR TITLE
Pull-in version 0.6.0 with Ruby 3.1 support

### PR DESCRIPTION
**Pull request by odlp**
Hello 👋 ,

We're trying to update our codebase to Ruby 3.1, but installing the `sq_mini_racer` gem fails:

```
~/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Libv8::Node::Location::Vendor (Psych::DisallowedClass)
	from ~/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/class_loader.rb:28:in `load'
	from ~/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:424:in `resolve_class'
	from ~/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:213:in `visit_Psych_Nodes_Mapping'
	from ~/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from ~/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from ~/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from ~/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
	from ~/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from ~/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from ~/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from ~/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
	from ~/.rubies/ruby-3.1.0/lib/ruby/3.1.0/psych.rb:370:in `load'
	from ~/.gem/ruby/3.1.0/gems/sq_mini_racer-0.3.1.0.6/ext/mini_racer_extension/vendor/gems/libv8-node-15.5.1.0.beta1-x86_64-darwin-20/ext/libv8-node/location.rb:18:in `block in load!'
	from ~/.gem/ruby/3.1.0/gems/sq_mini_racer-0.3.1.0.6/ext/mini_racer_extension/vendor/gems/libv8-node-15.5.1.0.beta1-x86_64-darwin-20/ext/libv8-node/location.rb:17:in `open'
	from ~/.gem/ruby/3.1.0/gems/sq_mini_racer-0.3.1.0.6/ext/mini_racer_extension/vendor/gems/libv8-node-15.5.1.0.beta1-x86_64-darwin-20/ext/libv8-node/location.rb:17:in `load!'
	from ~/.gem/ruby/3.1.0/gems/sq_mini_racer-0.3.1.0.6/ext/mini_racer_extension/vendor/gems/libv8-node-15.5.1.0.beta1-x86_64-darwin-20/lib/libv8/node.rb:8:in `configure_makefile'
	from extconf.rb:260:in `<main>'
```

Upstream in the `mini_racer` repo version 0.6.0 has been released ([changelog](https://github.com/rubyjs/mini_racer/blob/2a7c5cccaa6ed1222a38c6a8efdd669a7897b1a2/CHANGELOG#L3-L8)), which includes Ruby 3.1 support.

Thanks!

### CODE REVIEW

**Comment by djpate** [comment]
this is blocking us as well. +1

**Comment by hachi8833** [comment]
This is blocking us, too! I expect the fix will be merged ASAP.

**Comment by lloeki** [comment]
Instead of updating the outdated sq_mini_racer (which is really troublesome to maintain and keep in sync with mini_racer) I updated the sqreen gem to depend on mini_racer >= 0.4.0 directly and released 1.25.0. Hope that helps.

**Comment by odlp** [comment]
Thanks @lloeki!

**Pull request closed without merging**
