### PR TITLE
Encoding perf optimization

### PR DESCRIPTION
**Pull request by Taiki-San**
This PR is a performance improvement where we move the UTF-8 encoding enforcement from the Ruby code of the agent, to the native extension. This result in a substantial (10-20%) performance improvement.

Also enforced the indentation to 4 spaces per indentation, instead of the mixed 4-spaces/8-wide tabs we had.

### CODE REVIEW

**Comment by cataphract** [comment]
One of the tests is failing:

```
Sqreen::MiniRacerTest#test_return_unknown [/home/glopes/repos/mini_racer/test/mini_racer_test.rb:292]:
Expected: "Undefined Conversion"
  Actual: "-4712-01-01"
```

I have an alternative implementation in https://github.com/sqreen/mini_racer/commit/a233c63e8b3f1a3cdb9bf0ff4c93f8e1f1c88862 , which checks for valid UTF-8 if that's the string encoding and treats it as latin1 if it's not valid UTF-8 or if the encoding is any other. This is not 100% functionally equivalent because it doesn't support encodings other than UTF-8/ISO-8859-1/ASCII, but it's enough to pass the tests on the ruby side. We could also add a "slow path" with the code you have here for other encodings and keep this one for the most common cases of UTF-8/ISO-8859-1/ASCII.

**Comment by Taiki-San** [comment]
I think the test is now irrelevant, as performing a conversion on types that support `.to_s` is now the expected behaviour. Should we remove the test?

The alternative implementation is super interesting! If we were to be a bit greedy, we probably could go conditionally with the AVX2 implementation. From what I measured in my benchmark:
- The original `eval` implementation was processing 829 requests per second
- The original `call` implementation was processing 855 requests per second (+ 3%)
- The `call` implementation with the encoding performed with Ruby calls sent from C was processing 938 requests per second  (+ 13%)
- The patch you sent using SSE is processing 988 requests per second (+ 19%)
- The patch you sent using AVX2 is processing 1016 requests per second (+ 23%)

**Comment by cataphract** [comment]
@Taiki-San 
1) **Support legacy encodings** — I'm not sure how frequent legacy encodings are in the wild. Windows-1252 probably still has some prevalence, but I don't think there are attacks we will miss because of treating windows-1252 as latin1 (the relevant characters are mapped to the same bytes). However, since you already wrote the code, the cost part of the cost-benefit analysis may be low enough for this to be worth it. I'll leave it to your consideration.

2) **AVX2** I didn't even attempt to test this because on a Haswell machine right now, but if the benefit is so large, we could include the two paths. By the way, the code is from https://github.com/lemire/fastvalidate-utf-8  , with a small adaptation for the non-AVX2 path to require just SSE 3, not SSE 4.1. It's apache licensed, and we'll need to update our LICENSE to comply with it.

**Comment by Taiki-San** [comment]
1. I feared a little bit that such a change would impact the performance of our fast path but we're already in an `else` condition so it should be fairly cheap. I think that, especially after the reach, we should be careful with string encoding so that JS can freely call string utils. I'll probably call the Ruby code in this case.

2. I think AVX2 was introduced with Haswell first but after deeper checks, the SSE3 → AVX2 performance difference is smaller than I thought (1.6% uplift instead of 2.8% as my first figure implied). Probably not worth it in regard to the complexity of supporting pre-Haswell platforms (chips released before 2013, or Xeon < v3).

I'll merge your branch in this PR and tidy every thing up.
As for the failing test, what should we do? Remove it?

**Comment by Taiki-San** [comment]
Yeah, the more I test, the least interesting it appears. I think we can safely ignore it for now and keep the override flag around in case it make sense for a specific customer.
The performance uplift is the largest on very long strings, but even then is of the realm of 1-2%.
From the look of things, the Travis tests are failing for reasons unrelated to the code. Do you want to add anything to this PR?

**Comment by cataphract** [comment]
@Taiki-San I'm going to rebase with without the whitespace changes to minimize the conflicts with upstream. We should also try to push this upstream to keep our delta low.

**Comment by Taiki-San** [comment]
@cataphract Ok. Do you want me to handle pushing this upstream?

**Comment by cataphract** [comment]
@Taiki-San 

> Ok. Do you want me to handle pushing this upstream

Yes, that would be great!

**Pull request merged**
